### ISSUE TITLE
Unable to parse when using js file instead of json

### ISSUE THREAD

**Issue by mibaraho** [bencevans/grunt-sequelize#22]
When trying to run grunt sequelize:migrate it throws:

> Warning: Unable to parse "./config/config.js" file (Unexpected token ' in JSON at position 0). Use --force to continue.

My config file is not a json but a javascript file (it reads some env variables). 

`'use strict';`

`var env = process.env.NODE_ENV || 'development';`
`var config = require('../server/config/environment/'+env);`

`module.exports = {`
`"development": {`
`"url": config.sequelize.uri,`
`"dialect": "mysql"`
`},`
`}`

I guess you are using JSON.parse instead of importing the file. It would be great to have this option too.

Best regards

**Comment by bencevans** [comment]
Hi Matius,

  

I no longer use this module but happy to add users to the projects if wishing
to use/maintain.

  

Kind regards,

  

Ben

![](https://link.nylas.com/open/ccdnajhyk0b7h8vev2g4lmfjo/local-8dd95f25-d398?
r=cmVwbHkrMDAwOWJlNDdmOGJhZDg2NDAyZDhhNjIwODBhMmRmNTMzMjc0Y2U2NDdiNjZkN2MyOTJj
ZjAwMDAwMDAxMTNjNTc0Nzc5MmExNjljZTBhMmVmZDMyQHJlcGx5LmdpdGh1Yi5jb20=)

  
On Aug 12 2016, at 12:26 pm, Matias Barahona <notifications@github.com> wrote:  

> When trying to run grunt sequelize:migrate it throws:

>

>> Warning: Unable to parse "./config/config.js" file (Unexpected token ' in
JSON at position 0). Use --force to continue.

>

> My config file is not a json but a javascript file (it reads some env
variables).

>

> `'use strict';`

>

> `var env = process.env.NODE_ENV || 'development';`  
`var config = require('../server/config/environment/'+env);`

>

> `module.exports = {`  
`"development": {`  
`"url": config.sequelize.uri,`  
`"dialect": "mysql"`  
`},`  
`}`

>

> I guess you are using JSON.parse instead of importing the file. It would be
great to have this option too.

>

> Best regards

>

> --  
You are receiving this because you are subscribed to this thread.  
Reply to this email directly, [view it on GitHub](https://github.com/bencevans
/grunt-sequelize/issues/22&r=cmVwbHkrMDAwOWJlNDdmOGJhZDg2NDAyZDhhNjIwODBhMmRmN
TMzMjc0Y2U2NDdiNjZkN2MyOTJjZjAwMDAwMDAxMTNjNTc0Nzc5MmExNjljZTBhMmVmZDMyQHJlcGx
5LmdpdGh1Yi5jb20=), or [mute the thread](https://github.com/notifications
/unsubscribe-auth/AAm-R2F1w9Yad-RxfKn2g-oPFTnCddBeks5qfFh3gaJpZM4Ji_8k&r=cmVwb
HkrMDAwOWJlNDdmOGJhZDg2NDAyZDhhNjIwODBhMmRmNTMzMjc0Y2U2NDdiNjZkN2MyOTJjZjAwMDA
wMDAxMTNjNTc0Nzc5MmExNjljZTBhMmVmZDMyQHJlcGx5LmdpdGh1Yi5jb20=).![](https://git
hub.com/notifications/beacon/AAm-
R2_y_t9_y8XYIF_GuEDJhMcDLmWhks5qfFh3gaJpZM4Ji_8k.gif)

**Comment by dpalma** [comment]
Fixed by 35986d0
